[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

[fuzz]
runs = 1000
max_test_rejects = 150000

[invariant]
runs = 1000
depth = 128

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
